.sonarcloud.properties, README.md, terraform/main.tf, zap/src/scan.py
test of sonarcloud scanning
See DSEC-511.
=> Enable sonarcloud DSEC-511

sdarq/backend/src/slacknotify.py
This PR will fix Sonarcloud findings.
=> [DSEC-518] Fix Sonarcloud findings

sdarq/backend/src/slacknotify.py, sdarq/frontend/src/app/cis-landing-page/cis-landing-page.component.css, sdarq/frontend/src/app/homepage/homepage.component.css, sdarq/frontend/src/app/security-controls/security-controls.component.css, sdarq/frontend/src/app/security-requests/security-requests.component.css, sdarq/frontend/src/index.html
This PR:
- Will fix Sonarcloud bugs
=> [DSEC-519] Fix Sonarcloud bugs

sdarq/frontend/src/app/jira-ticket-risk-assesment/form.json
This PR:
- Makes the `due date` a required field in JTRA questionnaire
=> [sdarq][JTRA]

docs/src/website/static/css/custom.css, sdarq/frontend/src/app/about-page/about-page.component.ts, sdarq/frontend/src/app/cis-landing-page/cis-landing-page.component.ts, sdarq/frontend/src/app/cis-results/cis-results.component.ts, sdarq/frontend/src/app/cis-scan/cis-scan.component.ts, sdarq/frontend/src/app/cis/cis.component.ts, sdarq/frontend/src/app/edit-security-controls-form/edit-security-controls-form.component.ts, sdarq/frontend/src/app/footer/footer.component.ts, sdarq/frontend/src/app/form/form.component.ts, sdarq/frontend/src/app/homepage/homepage.component.ts, sdarq/frontend/src/app/jira-ticket-risk-assesment/jira-ticket-risk-assesment.component.ts, sdarq/frontend/src/app/mainpage/mainpage.component.ts, sdarq/frontend/src/app/navbar/navbar.component.ts, sdarq/frontend/src/app/notfound/notfound.component.ts, sdarq/frontend/src/app/security-controls-form/security-controls-form.component.ts, sdarq/frontend/src/app/security-controls-list/security-controls-list.component.ts, sdarq/frontend/src/app/security-controls/security-controls.component.ts, sdarq/frontend/src/app/security-pentest/security-pentest.component.ts, sdarq/frontend/src/app/security-requests/security-requests.component.ts, sdarq/frontend/src/app/service-scan/service-scan.component.ts, sdarq/frontend/src/app/services/convert-json-to-csv/csv-data.service.ts, sdarq/frontend/src/app/threat-model/threat-model.component.ts, sdarq/frontend/src/styles.css
This PR:
- Improves code according to Sonarcloud findings.
=> [sonarcloud] Improvement

docs/src/docs/defectdojo_codedx.md, docs/src/docs/zap_scan.md
This PR:
Update public documentation about changes related to the ZAP scanner that affects DefectDojo and Sdarq.
=> [documentation] Update docs with zap scans changes

docs/src/docs/zap_scan.md
This PR:
- Edit docs page for Zap Scan
=> [docs][zap]

sdarq/frontend/src/app/security-controls-list/security-controls-list.component.html
This PR improves Sdarq UI for security controls list
=> [sdarq] UI Security controls improvement

sdarq/backend/src/schemas/edit_security_controls_schema.py, sdarq/backend/src/schemas/security_controls_schema.py, sdarq/frontend/src/app/edit-security-controls-form/edit-security-controls-form.component.html, sdarq/frontend/src/app/edit-security-controls-form/edit-security-controls-form.component.ts, sdarq/frontend/src/app/edit-security-controls-form/form.json, sdarq/frontend/src/app/form/form.component.ts, sdarq/frontend/src/app/models/service-security-control.model.ts, sdarq/frontend/src/app/pipes/filtersct.pipe.ts, sdarq/frontend/src/app/security-controls-form/form.json, sdarq/frontend/src/app/security-controls-list/security-controls-list.component.html, sdarq/frontend/src/app/security-controls-list/security-controls-list.component.ts
This PR:
- Edits security controls list
=> [sdarq][frontend][backend] Edit security-controls list 

sdarq/frontend/src/app/pipes/filtersct.pipe.ts, sdarq/frontend/src/app/security-controls-form/form.json, sdarq/frontend/src/app/security-controls-list/security-controls-list.component.html
This PR:
- Edits search function for security controls.
=> [sdarq] Edit search pipe

zap/requirements.txt, zap/src/scan.py
accidentally committed to master. reverting to previous state.
=> reverting accidental commit

sdarq/frontend/nginx.conf, sdarq/frontend/src/app/jira-ticket-risk-assesment/jira-ticket-risk-assesment.component.ts
This PR:
Fixes the reported problem when a user downloads the responses from `jira-ticket-risk-assessment` questionnaire
=> [sdarq] Fix download-pdf in JTRA

sdarq/frontend/src/app/security-controls-list/security-controls-list.component.html, sdarq/frontend/src/app/security-controls-list/security-controls-list.component.ts, sdarq/frontend/src/styles.css
This PR:
- Adds tooltips to security controls
=> Add tooltips in security controls page

sdarq/frontend/src/app/app-routing.module.ts, sdarq/frontend/src/app/app.module.ts, sdarq/frontend/src/app/apps-mainpage/apps-mainpage.component.html, sdarq/frontend/src/app/apps-mainpage/apps-mainpage.component.spec.ts, sdarq/frontend/src/app/apps-mainpage/apps-mainpage.component.ts, sdarq/frontend/src/app/navbar/navbar.component.html
This PR:
- Introduces apps main page that sends user to the questionnaire
=> [DSEC-536] Sdarq apps mainpage

sdarq/frontend/src/app/security-controls-form/form.json, sdarq/frontend/src/app/security-controls-list/security-controls-list.component.html, sdarq/frontend/src/app/security-controls-list/security-controls-list.component.ts
This PR:
- Will show TM with a light green check, even if there is not a link.
=> [sdarq] Fix TM

batch/Dockerfile, cis/Dockerfile, zap/Dockerfile
This PR:
- Changes Batch base image to alpine that does not have any finding reported by Trivy
=> Base images

sdarq/frontend/package-lock.json
This PR:
- Updates `engine.io` and `loader-utils` to address new findings from dependabot
=> [sdarq] Update dependencies

sdarq/backend/Dockerfile, sdarq/backend/src/app.py, sdarq/backend/src/schemas/security_controls_schema.py, sdarq/backend/src/slacknotify.py, sdarq/frontend/src/app/app-form/app-form.component.ts, sdarq/frontend/src/app/form/form.component.ts, sdarq/frontend/src/app/security-controls-list/security-controls-list.component.html, sdarq/frontend/src/app/security-controls-list/security-controls-list.component.ts
This PR:
- Adds settings for Gunicorn parallel workers to add more security
- Fix warnings in Kubernetes pods logs for slack messages in the backend
- Create new security template when there is a new app (so far it has been just for new services)
- Adds DefectDojo product link to security controls when a new app or new service is created.
=> [sdarq] Add more automation

sdarq/frontend/package-lock.json, sdarq/frontend/package.json
This PR:
- Updates `babel-loader` and `json5` dependencies
=> [sdarq] Update babel-loader and json5

security-controls/entrypoint.py
This PR:
-  Increases response limit to get all products with the predefined tag
=> Increase response limit

docs/src/docs/secret_deplyment.md, security-controls/deploy.sh, security-controls/deployment.yaml
This PR: 
Fix env variables for the `security-controls` namespace in GKE
=> [seccon] Fix env

batch/Dockerfile, batch/entrypoint.py, batch/requirements.txt, cis/entrypoint.py, cis/requirements.txt, sdarq/backend/requirements.txt, sdarq/backend/src/app.py, sdarq/backend/src/parse_data.py, sdarq/backend/src/schemas/edit_security_controls_schema.py, sdarq/backend/src/schemas/manual_pentest_request_schema.py, sdarq/backend/src/schemas/new_app_schema.py, sdarq/backend/src/schemas/new_service_schema.py, sdarq/backend/src/schemas/security_controls_schema.py, sdarq/backend/src/schemas/threat_model_request_schema.py, sdarq/backend/src/schemas/zap_scan_schema.py, sdarq/backend/src/slacknotify.py, sdarq/frontend/src/app/app-form/form.json, sdarq/frontend/src/app/edit-security-controls-form/edit-security-controls-form.component.html, sdarq/frontend/src/app/edit-security-controls-form/edit-security-controls-form.component.ts, sdarq/frontend/src/app/edit-security-controls-form/form.json, sdarq/frontend/src/app/form/form.json, sdarq/frontend/src/app/jira-ticket-risk-assesment/form.json, sdarq/frontend/src/app/security-controls-form/form.json, sdarq/frontend/src/app/security-pentest/form.json, sdarq/frontend/src/app/service-scan/form.json, sdarq/frontend/src/app/threat-model/form.json, sdarq/frontend/src/styles.css
This PR:
- Do not ask users for the security champion but gets the user email via IAP
- Updates regex for the URLs
- Since some of the security controls are auto-updated, the edit security control UI and endpoint reflects the update only for the security controls that are not auto-updated. 
- Change basic logging to `google.logging`
=> [sdarq][frontend][backend] Code improvements

sdarq/backend/src/schemas/manual_pentest_request_schema.py, sdarq/backend/src/schemas/new_app_schema.py, sdarq/backend/src/schemas/new_service_schema.py, sdarq/backend/src/schemas/security_controls_schema.py, sdarq/backend/src/schemas/threat_model_request_schema.py, sdarq/frontend/src/app/app-form/form.json, sdarq/frontend/src/app/form/form.json, sdarq/frontend/src/app/security-controls-form/form.json, sdarq/frontend/src/app/security-pentest/form.json, sdarq/frontend/src/app/threat-model/form.json
This PR:
- Increases the length of the input field for Service name
=> [DSEC-626] Increase the length of the input field

sdarq/backend/src/app.py, sdarq/backend/src/schemas/cis_scan_schema.py, sdarq/frontend/src/app/cis-scan/form.json
This PR:
- Increase the length of the project id name for CIS scanner module
=> [sdarq] Edit project id pattern

sdarq/frontend/package-lock.json
This PR:
- Update `webpack 5` to a non vulnerable version
=> [sdarq][frontend] Update webpack 5

zap/src/scan.py
Not all zap scans have coded projects. This PR updates the slack messages to include the target URL of the service, instead of the CodeDX project name, which might not exist.
=> Zap Scans: Update slack messages to not require a codedx project name

sdarq/backend/src/app.py
This PR:
- Improves `request_manual_pentest` endpoint
=> [sdarq][backend] Improve SDARQ backend endpoints

sdarq/backend/src/app.py, sdarq/frontend/src/styles.css
This PR: 
- Improves 
- `\get_sec_controls_service`
- `\health`
- `\get_sec_controls`
=> [DSEC-642][sdarq][backend] Improve endpoints

sdarq/backend/src/app.py, sdarq/backend/src/security_headers.py
This PR:
- Refactor some part of the backend code
=> [sdarq][backend]

sdarq/frontend/src/app/security-controls-list/security-controls-list.component.html
=> [sdarq] Single page security controls

sdarq/backend/src/app.py, sdarq/frontend/src/app/form/form.json, sdarq/frontend/src/app/jira-ticket-risk-assesment/form.json, sdarq/frontend/src/app/jira-ticket-risk-assesment/jira-ticket-risk-assesment.component.html, sdarq/frontend/src/app/jira-ticket-risk-assesment/jira-ticket-risk-assesment.component.ts
This PR:
- Edit JTRA questionnaire to generate results after submitting the ticket
=> [DSEC-662][SDARQ] Calculate risk after submitting the questionnaire

sdarq/frontend/src/app/form/form.json
This PR:
- Fixes compliance question
=> [sdarq][frontend] Improve compliance section

sdarq/backend/src/schemas/new_app_schema.py, sdarq/backend/src/schemas/new_service_schema.py, sdarq/frontend/src/app/app-form/form.json, sdarq/frontend/src/app/form/form.json
This PR:
- Validates Jira Ticket Key ID
=> [DSEC-663][sdarq] Validate JIra Ticket key ID

zap/requirements.txt
This PR:
- Updates `requests` for ZAP scans
=> [zap] Update requests

sdarq/frontend/package-lock.json
This PR:
- Updates SDARQ dependencies to a non vulnerable version
=> [sdarq][frontend] Address dependency vulns for SDARQ

sdarq/backend/src/app.py
This PR:
- Replaces all `Response(json.dumps(data))` with `jsonify` since the latter returns a Flask Response object with the JSON response and sets the appropriate content type header.
=> [sdarq][backend] Code refinement

sdarq/frontend/package-lock.json, sdarq/frontend/package.json
This PR:
- Upgrade `word-wrap` and `angular-devkit/build-angular`
=> [sdarq][frontend] Upgrade word-wrap dependency

sdarq/backend/src/app.py, sdarq/backend/src/dojo_helper.py, sdarq/backend/src/slacknotify.py
This PR:
- Improves Slack notifications when there is a product update
=> [sdarq][backend] Improve notifications for product updates

sdarq/frontend/package-lock.json, sdarq/frontend/package.json
This PR:
- Upgrades SDARQ frontend dependencies
=> [sdarq] Upgrade dependecies

sdarq/backend/src/app.py, sdarq/backend/src/slacknotify.py
This PR:
- Alerts the AppSec team when there are exceptions in the `submit` and `submit_new_app` endpoints.
=> [DSEC-691][sdarq][backend] Add alerting when there are exceptions

zap/src/scan.py
LeoApps now can be scanned like UI scans, and need to have their scan XML uploaded in order to be eligible for the full ConMon experience.
=> [DSEC-685] add leoapps to xml uploads

docs/src/docs/cis_scan.md, docs/src/docs/configurations.md, docs/src/docs/sdarq.md, docs/src/docs/secret_deplyment.md, docs/src/docs/zap_scan.md
=> [Docs] Update docs

codedx/Dockerfile
troubleshoot codedx - looks like there was a major upgrade to 8.0, so rolling it back
=> pin codedx to v2023.4.8

cis/Dockerfile, cis/entrypoint.py, cis/slacknotifications.py
This PR:
- Notifies AppSec team if an error is raised while scanning GCP projects with CIS Scanner
=> [DSEC-705] Cis error alerts

defectdojo/Dockerfile.django
Quarterly update to defect dojo. Manually tested for deduplication of results and the scarf workflows that touch dojo (new service creation and requesting an individual zap scan). Also ran a weekly scan run in dev without issue.
=> [DSEC-711] update dojo version to latest

cis/deployment.yaml, docs/src/docs/sdarq.md, security-controls/deployment.yaml, terraform/modules/node-pool/main.tf, zap/deployment.yaml
This PR:
- Removes deprecated versions of APIs in cluster
=> [DSEC-712][cluster] Remove deprecated versions

sdarq/backend/src/app.py, sdarq/backend/src/slacknotify.py
This PR:
- Sends notifications to the team in case there is an exception in SDARQ's endpoints
=> [DSEC-713] Add SDARQ notifications in case there are endpoints exceptions

sdarq/backend/src/schemas/edit_security_controls_schema.py, sdarq/backend/src/schemas/new_service_schema.py, sdarq/backend/src/schemas/security_controls_schema.py, sdarq/frontend/src/app/edit-security-controls-form/form.json, sdarq/frontend/src/app/form/form.json, sdarq/frontend/src/app/security-controls-form/form.json, sdarq/frontend/src/app/security-controls-list/security-controls-list.component.html, sdarq/frontend/src/app/security-controls-list/security-controls-list.component.ts, sdarq/frontend/src/app/security-controls/security-controls.component.html
This PR:
- Fixes the validation of the GitHub link field in the new service questionnaire. This validation should be aligned with security controls forms
=> [DSEC-741][DSEC-742][SDARQ] Fix SDARQ new service github link field validation

sdarq/frontend/src/app/homepage/homepage.component.css, sdarq/frontend/src/app/homepage/homepage.component.html
This PR:
- Updates the frontpage of SDARQ
=> [DSEC-745][sdarq] Update frontpage

sdarq/backend/src/schemas/threat_model_request_schema.py, sdarq/frontend/src/app/threat-model/form.json
This PR:
- Fix patterns for threat model requests questionnaire fields, since it shows as an error in pods logs
=> [SDARQ] Fix patterns for threat model requests questionnaire fields

cis/Dockerfile, cis/deployment.yaml, cis/entrypoint.py, sdarq/backend/Dockerfile, sdarq/backend/src/app.py
This PR:
- Fix the bug when user does not provide slack channel to CIS scanner
=> CIS troubleshoot

sdarq/frontend/src/app/cis-scan/form.json
This PR:
- Edits CIS scan page text.
=> [SDARQ] Edit CIS scan page text

sdarq/frontend/package-lock.json
This PR:
- Updates `@adobe/css-tools` dependency to `4.3.2` version
=> [sdarq] Update @adobe/css-tools

sdarq/frontend/package-lock.json
This PR:
- Update `follow-redirects` dependency
=> [DSEC-760][sdarq][frontend] Update follow-redirects dependency

sdarq/deployment.yaml
This PR attempts to fix resource unavailability for SDARQ
=> First attempt to fix SDARQ

zap/deployment.yaml, zap/src/trigger.py
Moves UI scans to weekly, the weekly cron to Thursday Morning, and removes the monthly cron as it is no longer needed.
=> [DSEC-765] Add UI zap scans to weekly cron

cis/deployment.yaml
This PR:
- Changes weekly scanning from Saturday to Thursday.
=> [DSEC-767][cis] Trigger scans weekly on Thursdays

zap/deployment.yaml, zap/requirements.txt, zap/src/drive_upload.py, zap/src/scan.py
Adds the ability to upload raw XML and CodeDx reports to the appropriate monthly folder in Google Drive. 
Changes include adding connecting to the google drive service, pulling the relevant folders, creating the folder structure from the flat list returned, and finding the appropriate folders within that structure for monthly uploads (changes every month).
=> [DSEC-763] add google drive upload

zap/deployment.yaml, zap/src/drive_upload.py, zap/src/scan.py, zap/src/trigger.py, zap/src/zap.py, zap/src/zap_scan_type.py
The ConMon reporting folders in google drive are not a standard folder, they are in shared drives. This changes the code to pull folders from the shared drive used for ConMon, as well as upload to that shared drive. 
It also adds the date to the ZAP xml report name.
=> [DSEC-763] change to using a shared drive.

cloudbuild.yaml, sdarq/backend/Dockerfile, sdarq/backend/src/app.py, sdarq/backend/src/authz_decorator.py, sdarq/backend/src/iap_userinfo.py, sdarq/deployment.yaml, sdarq/frontend/nginx.conf, sdarq/frontend/src/app/app-routing.module.ts, sdarq/frontend/src/app/app.component.ts, sdarq/frontend/src/app/app.module.ts, sdarq/frontend/src/app/authz.guard.spec.ts, sdarq/frontend/src/app/authz.guard.ts, sdarq/frontend/src/app/navbar/navbar.component.html, sdarq/frontend/src/app/navbar/navbar.component.ts, sdarq/frontend/src/app/services/authz/authz.service.spec.ts, sdarq/frontend/src/app/services/authz/authz.service.ts, sdarq/ingress.yaml
This PR introduces:
- Authorization in SDARQ
=> [DSEC-761][sdarq] SDARQ authz

zap/src/scan.py
Uploading ui scan reports to google drive is failing in prod, but not in dev. Adding more logging in order to better understand the issue.
=> Add more logging for drive upload

zap/src/drive_upload.py, zap/src/scan.py, zap/src/trigger.py, zap/src/zap.py
Fixing the issue where report upload to google drive was failing.
=> [DSEC-799]

sdarq/frontend/package-lock.json
This PR:
- Update `follow-redirects` dependency
=> [sdarq] Update dependency

sdarq/frontend/package-lock.json
This PR:
- Updates dependencies
=> [sdarq] Update deps

sdarq/frontend/src/app/form/form.json, sdarq/frontend/src/app/terra-new-service/form.json
This PR:
- Removes Tcell tool integration from the questionnaires
=> Tcell update

.gitignore, codeql.yaml
Create an advanced codeql config to scan python and javascript and typescript
=> DRAFT - CodeQL scan

defectdojo/Dockerfile.django
Quarterly update to defect dojo
=> [DSEC-808] update dojo version

sdarq/frontend/src/app/terra-new-service/form.json, sdarq/frontend/src/styles.css
This PR:
- Adds an alert without condition for every new service. This also addresses the Jira Ticket creation when there are no alerts generated.
=> [sdarq] Fix cases when no alerts are generated

zap/requirements.txt
This PR updates `aiohttp` to `3.9.4`
=> [zap] Update dependencies

cis/entrypoint.py
This PR:
- Filters CIS findings by Level 1
=> [cis] Filter notifications from Level 1 and High Impact

zap/src/drive_upload.py, zap/src/scan.py
Updating the script to properly reflect that the ConMon meeting is on the fourth Wednesday of the month. 
This is the uploaded file from the test I ran this afternoon.
https://drive.google.com/drive/folders/1t0oRtd2HZcCmobn4BLHy_oHJM2_tQNo_
=> update date math

cis/entrypoint.py
This PR introduces:
Changes in CIS scanner by reporting Level 2 findings
=> [DSEC-908][cis] Report level 2 findings in slack channel

sdarq/frontend/package-lock.json
This PR: 
- Updates SDARQ frontend dependecies
=> [DSEC-912][sdarq] Update dependencies

zap/src/defectdojo_apiv2.py, zap/src/drive_upload.py, zap/src/scan.py, zap/src/zap.py
Increases retry back off for the main scan loop, changes defect dojo helper code to not check for response codes for exceptions. This was causing an exception.
=> Attempt to increase monthly scan reliability

batch/entrypoint.py, zap/src/drive_upload.py, zap/src/scan.py
Adds a slack alert when no findings have been found, just to show in slack that the scan ran. Some clean up of logging and catching an exception if the slack channel doesn't exist.
=> add slack alerts when no findings

sdarq/frontend/package-lock.json, sdarq/frontend/src/app/edit-security-controls-form/edit-security-controls-form.component.ts, sdarq/frontend/src/app/services/survejs-form/survey.component.ts
The forms for editing controls were not being properly updated when a service was selected. The fixes in this PR were taken from https://github.com/broadinstitute/dsp-appsec-infrastructure-apps/pull/558, and they are currently working.
=> [DSEC-899] Fix scan submission survey

sdarq/backend/requirements.txt, sdarq/backend/src/app.py, shared/global.sh, zap/src/scan.py
Updates Werkzeug and Flask, as well as removes the outdated flask-api.
Removing flask_api surfaced an existing issue that hadn't previously been flagged by Sonar. This issue is enough work to fix that it will be a separate PR.
=> [DSEC-932] updates Werkzeug and Flask.

zap/src/scan.py
Small change to include escalated in the raw reports.
=> [dsec-956] add escalated findings to raw reports

zap/deployment.yaml, zap/src/zap.py
adding an extra scan type to the hail scans pipeline.
=> [DSEC-945] add hailapi to scans

zap/deployment.yaml, zap/src/drive_upload.py, zap/src/scan.py, zap/src/zap.py
adds the ability for hail scans to uploaded to the correct google drive folder. 
Test upload location is here https://drive.google.com/drive/folders/1wd0XWgGBNpo0IyYsJTU_3LCTMKojrvRP?usp=sharing
The new location is not a shared drive on google, so the api calls are a little different.
=> [dsec-961] add gdrive uploads for hail

zap/src/scan.py
Removes grouping by status and finding name, so each unique finding is a row in the exported CSV.
=> [DSEC-966] remove grouping by status
