broadinstitute/dsp-appsec-infrastructure-apps

zap/src/scan.py
zap/src/trigger.py

It is currently necessary to link a codedx project when setting up a scan to run with zap. This PR removes the requirement. It will still work with Codedx, but it will not longer be necessary.

remove codedx requirement

---

sdarq/frontend/Dockerfile

This PR:
- Replaces SDARQ frontend old-based image with the AppSec blessed image without vulnerabilities [nodejs:14-alpine]

[sdarq] Add blessed docker image for frontend

---

zap/src/trigger.py

New scan tags were added to defect dojo in dev, and this was causing scans to fail (currently the problem is only in dev). This change allows tags that are not in the scan tag enum to exist, without pushing them to the scanners.

DSEC-560 Fix enum exception

---

cloudbuild.yaml
sdarq/frontend/src/app/app-form/app-form.component.ts
sdarq/frontend/src/app/form/form.component.ts
security-controls/Dockerfile
security-controls/deployment.yaml
security-controls/entrypoint.py
security-controls/notify.py
security-controls/requirements.txt

This PR:
- Deploys a CronJob in the GKE cluster that runs weekly
- The CronJob will report in a Slack channel all security controls that are not implemented/integrated for a service/app
- In case some security controls should not be reported weekly (or in case there is a false positive), an AllowList `SECURITY_CONTROLS_IGNORE` is added to the cloud build.
- When a new service/app is created through questionnaires, some security controls will be set to false automatically and reported to the Slack channel as reminders.

[DSEC-586] Add alerts for missing security controls

---

sdarq/frontend/package-lock.json

This PR:
- Bumps [http-cache-semantics](https://github.com/kornelski/http-cache-semantics) from 4.1.0 to 4.1.1.

[sdarq][frontend] Update HTTP cache semantics

---

security-controls/Dockerfile
security-controls/notify.py

Security Control alerts generate a lot of noise that can be difficult to parse through. This is an attempt to try and make them more actionable.

Condense alerts

---

sdarq/backend/requirements.txt

This PR:
- Updates FLASK from `2.3.1` to `2.3.2` to address [CVE-2023-30861](https://github.com/advisories/GHSA-m2qf-hxjv-5gpq)

[sdarq][backend] Update flask

---

zap/src/terra_auth.py
zap/src/trigger.py
zap/src/zap.py

The first step to being able to scan Leo apps in azure is to ensure that the service account being used is registered and has accepted the TOS. 
Because we scan in both dev and prod, it selects which environment to register with based on the url of the service being scanned. 
Checking this every scan due to it being low overhead and ensures that the scan is run with a registered and TOS accepting user.

[DSEC-654] Prepare zapscans for azure apps

---

bastion/Dockerfile
batch/Dockerfile
defectdojo/Dockerfile.django

Rolls back dojo version to 2.21.1
This version includes the UI fix for closing old findings product wide, but does not include the bug that was introduced in 2.22.0. The bug causes most findings on import to close, leaving only one or two open. It is not clear why only a couple are left open, but it is clear that findings that are still present should not be closed.

roll back dojo version

---

defectdojo/Dockerfile.django
sdarq/frontend/src/app/form/form.component.html

Updates DefectDojo to latest release which contains the fix for the import findings bug we were experiencing. 
Removes the banner advertising that new product isn't working in SDARQ.
Tested creating a new product as well as importing findings.

[DSEC-672] Update dojo and remove banner

---

zap/src/trigger.py

Terra prod was being skipped on the monthly runs due to page limits of the query fetching tagged endpoints from dojo. Added more search terms to the query to limit the number of endpoints returned.

[DSEC-652] add tag to query string in trigger.py

---

batch/Dockerfile
sdarq/backend/src/app.py
sdarq/backend/src/dojo_helper.py

Currently if a product already exists in DefectDojo the new product questionnaire fails when you submit it. There are valid scenarios where the product has already been created before the engineering team submits the form, and it would be nice if submitting the form updated the project if it didn't exist. 
This PR moves the call for creating a new dojo project into a helper function, and adds checking to see if the project already exists. If it does, the description is updated with the new information provided in the questionnaire.

make product creation more robust

---

zap/requirements.txt

This PR:
- Upgrades `aiohttp` to a non-vulnerable version

[zap] Upgrade aiohttp

---

sdarq/backend/src/app.py
sdarq/backend/src/dojo_helper.py
sdarq/backend/src/jiranotify.py
sdarq/backend/src/slacknotify.py

This PR:
- Creates DefectDojo product even if the dev team Jira ticket is not created successfully
- Extends `jiranotify` file to create a Jira task ticket and if it fails it tries to create a Jira story ticket
- Removes the Jira ticket link in the Slack notification
- If there are exceptions, they are reported to a Slack channel

[DSEC-687][sdarq][backend] Fix Jira ticket creation

---

zap/deployment.yaml
zap/src/scan.py
zap/src/terra_auth.py
zap/src/zap.py

This is a little big. It introduces a new scan type, LEOAPP, in order to support azure apps launched by Leo. To support this new type it adds contexts to zap scans and sets cookies for LeoApps.

[DSEC-654] Add context and cookie auth to zap scans

---

zap/src/scan.py
zap/src/trigger.py
zap/src/zap.py
zap/src/zap_scan_type.py

Puts the scan type enum into its own file, allowing for globals with environment variables in the zap.py file. (This was previously blocked by trigger.py importing zap.py without having the correct env vars available.)

refactor scan type

---

cis/Dockerfile
cis/entrypoint.py
cis/inspec_ruby_3.1.patch

Fixing Inspec incompatibilities due to Ruby 3.1 version upgrade in the latest base blessed image

[cis] Use Broadinstitute fork for GKE benchmark

---

cis/deployment.yaml
cis/entrypoint.py
cis/scanweekly.py
cloudbuild.yaml

This PR:
- Will allow CIS scanner to run weekly only against prod projects
Added a variable in the trigger with all prod projects, the name is `_CIS_PROD_PROJECTS`, and we can add or remove the prod projects just by editing the value of that variable.

[DSEC-699] CIS scanner weekkly only for prod projects

---

sdarq/frontend/src/app/app.module.ts
sdarq/frontend/src/app/edit-security-controls-form/edit-security-controls-form.component.css
sdarq/frontend/src/app/edit-security-controls-form/edit-security-controls-form.component.html
sdarq/frontend/src/app/edit-security-controls-form/edit-security-controls-form.component.ts
sdarq/frontend/src/app/edit-security-controls-form/form.json
sdarq/frontend/src/app/services/edit-survey/editsurvey.component.ts

The edit security control survey required a user to copy and paste the existing values back into the survey form. This is a small change that fills in the previous values so they don't need to be copy and pasted.

[sdarq][frontend] Updates and pre-fills the edit sec control survey

---

sdarq/backend/requirements.txt
sdarq/backend/src/app.py
sdarq/backend/src/schemas/edit_security_controls_schema.py
sdarq/frontend/src/app/edit-security-controls-form/form.json
sdarq/frontend/src/app/security-controls-list/security-controls-list.component.ts

This PR:
- Edits regex pattern for the cases when the user does not provide a URL or it has space strings
- During the development process, Gunicorn workers failed to start, so it required some investigation that led to `markupsafe` addition in the `requirement.txt`

[DSEC-723][sdarq][backend] Edit regex for security controls edit form

---

sdarq/backend/Dockerfile
zap/Dockerfile
zap/deployment.yaml

ZAP is no longer an OWASP project, and the docker image location has changed. Updating to the new image location. 
A test scan was requested from SDARQ and a monthly scan was also run manually.

[DSEC-734] update zap image location

---

sdarq/backend/src/app.py
sdarq/backend/src/schemas/edit_security_controls_schema.py
sdarq/backend/src/schemas/new_service_schema.py
sdarq/backend/src/schemas/security_controls_schema.py
sdarq/backend/src/schemas/threat_model_request_schema.py
sdarq/frontend/src/app/app-routing.module.ts
sdarq/frontend/src/app/app.module.ts
sdarq/frontend/src/app/delete-service-security-controls/delete-service-security-controls.component.html
sdarq/frontend/src/app/delete-service-security-controls/delete-service-security-controls.component.spec.ts
sdarq/frontend/src/app/delete-service-security-controls/delete-service-security-controls.component.ts
sdarq/frontend/src/app/delete-service-security-controls/form.json
sdarq/frontend/src/app/navbar/navbar.component.html
sdarq/frontend/src/app/services/delete-service-security-controls/delete-service-security-controls.service.spec.ts
sdarq/frontend/src/app/services/delete-service-security-controls/delete-service-security-controls.service.ts
sdarq/ingress.yaml

This PR:
- Adds a feature that removes a service from security controls

[DSEC-743][sdarq][backend][frontend] Add remove endpoint and service for SecCon

---

sdarq/backend/src/schemas/new_app_schema.py
sdarq/frontend/src/app/app-form/form.json

This PR:
- Edits the `Github` field validation to accept `N/A` or `https://github/orgname/repo`  as a value

[sdarq] Edit Github field validation

---

cis/Dockerfile

This PR:
- Installs a specific version of `inspec-bin` to run CIS Scanner

[DSEC-750][CIS] Change version

---

.gitignore
.vscode/settings.json
zap/deployment.yaml
zap/requirements.txt
zap/src/zap.py

Changes to ZAP report download to allow for scope. The previous version of report generation would report all findings independent of the intended scope of the scan. The new version restricts findings to those sites that are provided to the zap_report() function.

[DSEC-759] Add scope to report download

---

zap/requirements.txt

Upgrade `aiohttp` from `3.9.0` to `3.9.2` for Zap

[zap] aiohttp upgrade to 3.9.2

---

zap/deployment.yaml

This PR:
- Moves `API` tag endpoint scans to monthly scans since there's no Compliance requirement for it.

[ZAP] Move API scans to monthly scans

---

cis/deployment.yaml
cis/scanweekly.py

This PR:
- Updates weekly CIS scanner to directly trigger a scan from the prod project list and not fetch all tables in BigQuery to check if they exist in the prod project list (old approach when we did not have a prod project list)

[cis] Change CIS weekly scanner logic

---

README.md
terraform/main.tf

This PR:
- Adds permissions to GKE cluster node Service Account, so nodes can pull images from Google Artifact Registry after migration from GCR

[DSEC-818] GCR to GAR migration

---

zap/deployment.yaml
zap/src/scan.py
zap/src/zap.py
zap/src/zap_scan_type.py

Add support for IAP token authentication to Zap scanning. 
This adds to new types to the scan types enum to support IAP UI scans and IAP API scans. New functionality for fetching the IAP token from google and adjusted the functionality for setting cookies. Both beehive and Sherlock have been scanned in dev successfully with the new scan types.

[DSEC-888] Add support for IAP authentication

---

sdarq/backend/src/app.py
sdarq/backend/src/schemas/zap_scan_schema.py
sdarq/frontend/src/app/service-scan/form.json

Removes the severity option from the scan submission form. Also removes sending codedx project information to the zap scan container, which stops it from being able to upload to codedx projects for off-cycle scans.

[DSEC-902] simplify zap scan request

---

zap/deployment.yaml
zap/src/scan.py
zap/src/zap.py
zap/src/zap_scan_type.py

Beehive uses cookies, but Sherlock does not. Making cookies optional so Sherlock can be scanned.
Also threw in exponential back off on closing defect dojo engagements.

Change scan types to better accommodate beehive and Sherlock

---

sdarq/backend/src/app.py

When a dev fils out the new service questionnaire several appsec tickets are created, but as of now there has not been one for adding ZAP scanning. This is a small change that adds that ticket.

[DSEC-917] Add dast ticket on product creation

---

cis/Dockerfile

cis scanner jobs fail with many failed python imports, and logs show the python version is 3.12
so pin it to 3.11

pin cis base image version

---

sdarq/frontend/package-lock.json

Brings in changes from Dependabot PRs 581 and 573. Those PRs can't be properly tested and merged because dependabot does not have access to our cloud build. 
Some manual testing was done to test these updates including new service checklist, jira ticket risk assessment, running a cis scan, and downloading a checklist response as a pdf.

[DSEC-932] SDARQ front end dependabot updates

---

zap/src/scan.py

Terra and other UI scan sites have changed the hash structure in their javascript and css resources. This small change allows our cleaning regex to recognize the new hash, and remove it from the report.

[DSEC-946] The hash used in the javascript pages for terra has changed, this updates our regex.

---

zap/src/zap.py

Added rate limiting to ZAP scanning to prevent sites like beehive from having connection errors during scanning.

[DSEC-955]add rate limiting to zap

---

zap/src/drive_upload.py
zap/src/scan.py
zap/src/zap.py

Several small pipeline changes to try and improve reliability. 
A new retry loop around creating an engagement in defect dojo. Several scans were consistently failing on this step, and hopefully this helps to alleviate this issue. 
Broke out the zap shutdown action, and tried to fix the intermittent timeout issue. 
The TIMEOUT_MINS value was increased by one. This value is used for communicating with the local instance of ZAP. There had been an increase in timeouts when connecting with ZAP from the zap-scans controller, and this is an attempt to reduce those timeouts.
The requestspersecond value was decreased by 1. This is across all scans as an attempt to reduce issues where the scanner was encountering 502 or 503 errors while scanning.

[DSEC-963] add retry loop

---

sdarq/frontend/src/app/app-routing.module.ts

Some older documentation has the path /cis/scan for starting a cis scan. This is an attempt to add an alternate route so old documentation is still valid.

add alternate route for cis scanning page

---

zap/src/scan.py

Hail's continuous monitoring will be run by a different team. This adds a summary CSV extract to the weekly run to help simplify the process of doing reporting. 
This has not been added to Terra, as the extract does not currently support the way those findings are stored in Codedx. Adding that functionality should be a future task, if we decide we want this extract for Terra as well.

[DSEC-965] add csv report for hail

---

zap/Dockerfile
zap/deployment.yaml

Zap has changes the container location again. This updates the location and uses the bare (slim) image for the zap scanner.

[dsec-969] Update zap container image location
